### ISSUE TITLE
Translation: PT - Portuguese

### ISSUE THREAD

**Issue by fititnt** [ncase/remember#5]
- Diff: https://github.com/fititnt/remember/pull/1/files?utf8=%E2%9C%93&diff=split
- Preview: https://fititnt.github.io/remember/pt.html

----
Edits: 
1. added links

**Comment by fititnt** [comment]
At https://github.com/fititnt/remember/pull/1/files?utf8=%E2%9C%93&diff=split, there is a pull request from that repository to another branch that serves only for use GitHub interface to see changes from original version in English to (Brazilian) Portuguese. Reviewers are welcome (even in future), and this screen could be specially helpfull. (Also, if someone wants some github/git help with another language, ping me here or at rocha@ieee.org; I'm even OK to a 1-to-1 call to help).

@ncase some languages will hit some smaller problems with long or short texts. For now I will just do a translation batch, but you and other can preview here https://fititnt.github.io/remember/pt.html

**Comment by fititnt** [comment]
For other native Portuguese speakers: I will try to look for translations that could work fine for non Brazilians. That can make sense even for non-Brazilians, so this could make a bit more impact on jokes and make the text more verbose.

I'm already in contact with devs from Angola (pt-AO) on Facebook.

Is possible that we will have at least two pull requests with the translations to Portuguese

**Comment by ramon-mendes** [comment]
Hey guys, anyone still working on this?
I noticed the preview at https://fititnt.github.io/remember/pt.html is a bit visually different from the oficcial site.

Maybe I sholud be redone to make it 100% correct?

**Comment by fititnt** [comment]
Nice, @ramon-mendes, if you think you can do it, let me first transfer the ownership of the repository, so you can take your time and finish the translation.

Both me and @Lawendt are likely to take more time on this translation, and we already are looking for someone else assume the place. But if you already interested, you can assume and still be listed as translator.

Just confirm to me, so I follow you and transfer the repository.

**Comment by ramon-mendes** [comment]
Yes, go ahead! I can take it

**Comment by fititnt** [comment]
Great

> Repository transfer to ramon-mendes requested

Since you will be now the main translator, can replace my name on the html. The commits already have reference for me and Luiz Wendt

**Comment by ramon-mendes** [comment]
I received no "transfer request". Are you transfering https://github.com/fititnt/remember/?

**Comment by fititnt** [comment]
This was my screen 

![captura de tela de 2019-02-14 23-43-24](https://user-images.githubusercontent.com/812299/52829085-89757900-30b2-11e9-8a55-d37177e6b2ca.png)

Then, I aborted and tried again, but now github shows an error

![captura de tela de 2019-02-14 23-44-32](https://user-images.githubusercontent.com/812299/52829117-a1e59380-30b2-11e9-805c-c5666ec4cbc8.png)


As I see, you already have a repository with the same name 'remember', so GitHub now will fail to transfer the full repository (with PRs and etc).

I guess you at least will have to **rename the remember repository you already have before I transfer to you**. If the error persists, we have to contact the GitHub staff. They normally respond pretty fast.

**Comment by ramon-mendes** [comment]
I removed the repository (a fork I had of https://github.com/ncase/remember),
try again plz

**Comment by fititnt** [comment]
> Repository transfer to ramon-mendes requested

**Comment by ramon-mendes** [comment]
I don't understand it. I received no request, and at my home screen it shows that I own /ncase/remember:
![screenshot_2](https://user-images.githubusercontent.com/44581176/52873978-6f31ae80-3137-11e9-815b-6b51493b70fc.png)

**Comment by fititnt** [comment]
Done. Wait a bit. I also explained in a way for the GitHub support that potentially could direct they to improve the documentation.

![captura de tela de 2019-02-16 06-41-42](https://user-images.githubusercontent.com/812299/52896992-09383c00-31b6-11e9-9aaa-108883f15782.png)

**Comment by fititnt** [comment]
@ramon-mendes here the response.

> GitHub Developer Support <developer@githubsupport.com> | GitHub Developer Support <developer@githubsupport.com> | 22:59 (26 minutes ago) |   |  
-- | -- | -- | -- | --
GitHub Developer Support <developer@githubsupport.com>
to Emerson | to Emerson
to Emerson

> Lesley (GitHub Developer Support)Feb 17, 12:59 AM UTC
> Hi Emerson,Thanks for writing in to GitHub Support!An email should be sent to the ramon-mendes account to accept the transfer. I'm wondering if this email was received?They would need to be logged into their account to accept the transfer.Please note, these links expire within 24 hours. If you're reading this email after 24 hours from when the transfer was initiated, please abort the transfer and initiate it again.I hope this helps. Please let us know if you need anything else!All the best, Lesley
Find answers to common questions and learn with other GitHub users in our new GitHub Community Forum

Also, I just aborted and requested the transfer again (for more time to accept). So if is just it, just check your email in less than 24 from this post.

**Comment by kimpastro** [comment]
Some status about this issue?

**Comment by ramon-mendes** [comment]
I am doing progress, it is like 60% translated

**Comment by kimpastro** [comment]
How can I help?

**Comment by ramon-mendes** [comment]
I don't think help would come handy, I just need to finish it
Anyway, I pushed my changes: https://github.com/ramon-mendes/remember/

**Comment by ramon-mendes** [comment]
I completed the translation!!
https://ramon-mendes.github.io/remember/pt.html
Can someone review?

**Comment by fititnt** [comment]
@ramon-mendes have some text size adjustments to be done, but at https://github.com/ramon-mendes/remember/pull/1 I guess you are already doing some of these changes.

**Comment by ramon-mendes** [comment]
...think now text size adjustment are all OK

**Comment by ramon-mendes** [comment]
I've recreated the Pull request with translations.txt file adjusted
https://github.com/ncase/remember/pull/28

**Comment by fititnt** [comment]
Merged!

<em lang="pt">Parabéns a todos os envolvidos. E muito obrigado!<sup>(pt)</sup></em>

This issue can be closed.
